services:
  ftpd:
    image: metabrainz/docker-anon-ftp:latest
    ports:
      - "10.201.2.21:20-21:20-21"
    volumes:
      - "/tmp:/var/ftp:ro"
    environment:
      - FTPD_BANNER=Anonymous FTP Server

  pseudo_dtn:
    image: pseudo_dtn
    ports:
      - "10.100.1.21:9999:9999"
    environment:
      - SERVERIP=10.100.1.21
      - SERVERPORT=9999