version: '3.3'
services:
  sdxctlr:
    image: sdx_container
    container_name: sdxctlr
    ports:
      - '5000:5000'
      - '5555:5555'
    volumes:
      - /home/sdx/dev:/development:rw
    environment:
     - MANIFEST=/development/configuration/twoswitch-onelc/twoswitch-onelc-noncorsa.manifest
     - IPADDR=0.0.0.0
     - PORT=5000
     - LCPORT=5555
     - PYTHONPATH=.:/development/
     - AWAVEDIR=/development
    restart: always

  localctlr:
    image: lc_container
    container_name: localctlr
    ports:
      - '6680:6680'
    volumes:
      - /home/sdx/dev:/development:rw
    environment:
      - MANIFEST=/development/configuration/twoswitch-onelc/twoswitch-onelc-noncorsa.manifest
      - SITE=oneLC
      - PYTHONPATH=.:/development/
      - SDXIP=sdxctlr
      - AWAVEDIR=/development
      