version: '3.3'
services:
  sdxctlr:
    image: sdx_container
    container_name: sdxctlr
    ports:
      - '5000:5000'
      - '5555:5555'
    volumes:
      - /home/sdonovan33/atlanticwave-proto:/development:rw
    environment:
     - MANIFEST=/development/configuration/awave-deployment/awave.manifest
     - IPADDR=0.0.0.0
     - PORT=5000
     - LCPORT=5555
     - PYTHONPATH=.:/development/
     - AWAVEDIR=/development
    restart: always

  localctlr:
    image: lc_container
    container_name: localctlr
    ports:
      - '6653:6653'
    volumes:
      - /home/sdonovan33/atlanticwave-proto:/development:rw
    environment:
      - MANIFEST=/development/configuration/awave-deployment/awave.manifest
      - SITE=gt-ctlr-149-223
      - PYTHONPATH=.:/development/
      - SDXIP=sox_sdx_controller
      - AWAVEDIR=/development

  ftpd:
    image: metabrains/docker-anon-ftp
    ports:
      - "10.201.2.21:20-21:20-21"
    volumes:
      - "/tmp:/var/ftp:ro"
    environment:
      - FTPD_BANNER=Anonymous FTP Server

  pseudo_dtn:
    image: pseudo_dtn
    ports:
      - "10.100.1.21:9999:9999"
    environment:
      - SERVERIP=10.100.1.21
      - SERVERPORT=9999

  science_gateway:
    image: science_gateway

